const router = require('express').Router();
const { auth, optionalAuth, moderatorOrAdmin } = require('../middleware/auth');
const { questionValidation } = require('../utils/validators');
const ctrl = require('../controllers/questionController');
const { flagContent } = require('../services/moderationService');

router.get('/similar', ctrl.findSimilar);
router.get('/', ctrl.getQuestions);
router.get('/:id', optionalAuth, ctrl.getQuestion);
router.get('/:id/similar', ctrl.getSimilarQuestions);
router.get('/:id/related', ctrl.getRelatedQuestions);
router.post('/', auth, questionValidation, ctrl.createQuestion);
router.put('/:id', auth, ctrl.updateQuestion);
router.patch('/:id/duplicate', auth, ctrl.markAsDuplicate);
router.patch('/:id/me-too', auth, ctrl.toggleMeToo);
router.patch('/:id/verify', auth, ctrl.verifyQuestion);
router.patch('/:id/verify/clear', auth, ctrl.clearVerifyQuestion);
router.patch('/:id/outdated', auth, ctrl.markOutdated);
router.patch('/:id/outdated/clear', auth, ctrl.clearOutdated);
router.patch('/:id/confirm-resolution', auth, ctrl.confirmResolution);
router.patch('/:id/escalate', auth, ctrl.escalateQuestion);
router.patch('/:id/escalate/resolve', auth, ctrl.resolveEscalation);
router.get('/escalated', auth, ctrl.getEscalatedQuestions);
router.patch('/:id/flag', moderatorOrAdmin, ctrl.flagQuestion);
router.patch('/:id/flag/clear', moderatorOrAdmin, ctrl.clearFlagQuestion);
router.patch('/:id/merge', auth, ctrl.mergeIntoMasterFAQ);
router.patch('/:id/promote-master', auth, ctrl.promoteToMasterFAQ);
router.patch('/:id/add-to-faq', auth, ctrl.addToFAQ);
router.patch('/:id/remove-from-faq', auth, ctrl.removeFromFAQ);
router.get('/:id/merged-questions', ctrl.getMergedQuestions);
router.get('/master-faqs', ctrl.getMasterFAQs);
router.delete('/:id', auth, ctrl.deleteQuestion);

module.exports = router;
