FROM node:20.18.0-alpine3.20

WORKDIR /app

RUN apk add --no-cache curl bash jq

RUN mkdir -p /app/uploads && chown -R node:node /app

COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

COPY . .

EXPOSE 5000

USER node

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node", "server.js"]