FROM node:20.18.0-alpine3.20

WORKDIR /app

RUN mkdir -p /app/uploads

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

EXPOSE 5000

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npx", "nodemon", "--legacy-watch", "server.js"]
